#!/usr/bin/perl -T

use strict;
use warnings;

my ($i, $j, $k, $sum) = (0, 0, 0, 0);
my $numpts = 64;
my @dat;

while (<>) {
	chomp;
	my ($x, $y) = split;
	if($y ne "??"){
		push @dat, [ $x, $y ];
		$i++;
	}
}

for ($j = $numpts; $j < $i; $j++){
	$sum = 0;

	for ($k = $j - $numpts; $k < $j; $k++){
		$sum += $dat[$k][1];
	}

	printf "%d %.2f\n", $dat[$j][0], $sum/$numpts;
}
