#!/usr/bin/perl -T

use warnings;
use strict;
use utf8;
use open qw(:std :utf8);
use Encode qw(encode decode);

my ($i, $j, $k, $sum) = (0, 0, 0, 0);
my $numpts = 64;
my $mid = $numpts / 2;
my @dat;

@ARGV = map { decode("UTF-8", $_) } @ARGV;

while (<>) {
	chomp;
	my ($x, $y) = split;
	if ($y ne "??") {
		push @dat, [ $x, $y ];
		$i++;
	}
}

for ($j = $numpts; $j < $i; $j++) {
	$sum = 0;

	for ($k = $j - $numpts; $k < $j; $k++) {
		$sum += $dat[$k][1];
	}

	printf "%d %.2f\n", $dat[$j - $mid][0], $sum / $numpts;
}
