#!/usr/bin/perl -T

use warnings;
use strict;

my ($num, $tsum) = (0, 0);

while (<>) {
	chomp;
	my ($x, $y) = split;
	if ($y ne "??") {
		$num++;
		$tsum += $y;
	}
}

my $avg = $tsum / $num;
printf "%.2f\n", $avg;
