#!/usr/bin/perl -T

use warnings;
use strict;
use utf8;
use open qw(:std :utf8);
use Encode qw(encode decode);

my ($num, $tsum) = (0, 0);

@ARGV = map { decode("UTF-8", $_) } @ARGV;

while (<>) {
	chomp;
	my ($x, $y) = split;
	if ($y ne "??") {
		$num++;
		$tsum += $y;
	}
}

my $avg = $tsum / $num;
printf "%.2f\n", $avg;
