#!/usr/bin/python3 -u

import RPi.GPIO as GPIO
import time, sys

sys.path.append('/home/ghz/wxlib')
import wxlib as wx

wx_dir = "/home/ghz/particle_weather"
count = 0
time0 = time1 = time.time()

GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

def trigger_count(channel):
	global count, time0, time1

	time1 = time.time()
	count += 1
	time2 = time1 - time0

	if(time2 > 60):
		ts = time.strftime("%Y%m%d%H%M%S", time.gmtime(float(time1)))
		dat_string = "%s %.2f cpm\n" % (ts, count/(60/time2))
		wx.write_out_dat_stamp(ts, 'data', dat_string, wx_dir)
		count = 0
		time0 = time.time()

GPIO.add_event_detect(17, GPIO.FALLING, callback=trigger_count, bouncetime=20)

try:
	while True:
		time.sleep(1)

except KeyboardInterrupt:
	GPIO.cleanup()   # clean up on ctrl c.
