#!/bin/sh
BASE_DIR="/home/ghz/particle_weather"
DATA_DIR="$BASE_DIR/data"
OUT_FILE="$BASE_DIR/plots/particles.html"
DY=`date +%Y`
DATE=`date +%FT%TZ`
TDATE=`date +%Y%m%d`

TOP='<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="60">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="https://darkdata.org/dd.css">
<link rel="icon" href="https://slackology.net/favicon.ico" type="image/png"/>
<title> Particle Weather from a balcony in Augsburg, Germany</title>
</head>
<body>
<center>
<h1>Background Radiation from Augsburg, Germany</h1>
See <a href="https://github.com/mcthoren/particle_weather/">here</a> for more info.<br>
<br>
Current Conditions (updates every ~60s):
<table borders>'

END="</table>
<br>
<img src=\"particle_cpm_8.png\"><br><br>
<img src=\"particle_cpm_8_avg.png\"><br><br>
<img src=\"particle_cpm_24.png\"><br><br>
<img src=\"particle_cpm_24_avg.png\"><br><br>
<img src=\"particle_cpm_DA.45.png\"><br><br>
<img src=\"particle_cpm_DA.png\"><br><br>
<img src=\"particle_cpm_MA.png\"><br><br>
</center>
<br> <br>
</body> </html>"

LASTLINE=` cat $DATA_DIR/$DY/data.$TDATE |tail -1`
CPM=`echo $LASTLINE |awk '{printf("%.2f", $2*1000/108)}'`

LASTLINEAVG=` cat $DATA_DIR/data.8.avg |tail -1`
AVG_CPM=`echo $LASTLINEAVG |awk '{printf("%.2f", $2*1000/108)}'`

LASTLINEAVG=` cat $DATA_DIR/data.8.avg.64 |tail -1`
AVG_CPM64=`echo $LASTLINEAVG |awk '{printf("%.2f", $2*1000/108)}'`

echo "$TOP" >$OUT_FILE

echo "<tr><td>Activity for Last ~1m:</td> <td>$CPM nGy/h</td></tr>" >>$OUT_FILE
echo "<tr><td>Average for Last ~16m:</td> <td>$AVG_CPM nGy/h</td></tr>" >>$OUT_FILE
echo "<tr><td>Average for Last ~64m:</td> <td>$AVG_CPM64 nGy/h</td></tr>" >>$OUT_FILE
echo "<tr><td>Last Update:</td> <td>$DATE</td></tr>" >>$OUT_FILE

echo "$END" >>$OUT_FILE
